# fly.toml app configuration file generated for rollie-dev on 2023-08-28T00:37:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rollie-dev"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  ENV_NAME = "production"
  LISTEN_HTTP = ":3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
